version: '3.8'
services:
  django_gunicorn:
    build: .
    volumes:
      - static:/static
    env_file:
      - .env
    ports:
      - "8000:8000"

  nginx:
    build: nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn

#  rabbit:
#    image: rabbitmq
#    ports:
#      - "5672:5672"
#      - "15672:15672"

volumes:
  static: