version: '3.8'
services:
  django_gunicorn:
    build: .
    image: pycrs/stinbank:latest
    volumes:
      - static:/app/static
      - media:/app/media
    environment:
      - SECRET_KEY=$${{ secrets.DJANGO_SECRET_KEY }}
      - TOTP_KEY=$${{ secrets.DJANGO_TOTP_KEY }}
      - RABBITMQ_HOST=rabbit
    ports:
      - "8000:8000"

  stin_nginx:
    build: nginx
    image: pycrs/stinbank-nginx:latest
    volumes:
      - static:/static
      - media:/media
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn

  rabbit:
    image: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  static:
  media: