# Generated by Django 4.1.7 on 2023-04-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_account_created_at_account_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('mujucet', 'MůjÚčet'), ('mujucet_plus', 'MůjÚčet PLUS'), ('mujucet_gold', 'MůjÚčet GOLD'), ('g2', 'Studentský účet G2')], default='g2', max_length=15),
            preserve_default=False,
        ),
    ]
