# Generated by Django 4.1.7 on 2023-04-01 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_account_name_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('mujucet', 'MůjÚčet'), ('mujucet_plus', 'MůjÚčet PLUS'), ('mujucet_gold', 'MůjÚčet GOLD'), ('g2', 'Studentský účet G2')], default=('mujucet', 'MůjÚčet'), max_length=15),
        ),
    ]
