# Generated by Django 4.1.7 on 2023-04-01 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_alter_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_number',
            field=models.CharField(default='6541', editable=False, max_length=14, unique=True),
            preserve_default=False,
        ),
    ]
