# Generated by Django 4.2 on 2023-04-03 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_alter_currencyrate_currency'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accountbalance',
            unique_together={('account', 'currency')},
        ),
        migrations.DeleteModel(
            name='UserPreferredCurrency',
        ),
    ]
