# Generated by Django 4.2 on 2023-04-06 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0009_alter_accountbalance_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('mujucet', 'MůjÚčet'), ('mujucet_plus', 'MůjÚčet PLUS'), ('mujucet_gold', 'MůjÚčet GOLD'), ('g2', 'Studentský účet G2')], default='mujucet', max_length=15),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3)),
                ('amount', models.FloatField()),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_accounts', to='bank.account')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_accounts', to='bank.account')),
            ],
        ),
    ]
