# Generated by Django 4.2 on 2023-04-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0011_transaction_created_at_alter_transaction_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbalance',
            name='default_balance',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='accountbalance',
            constraint=models.UniqueConstraint(condition=models.Q(('default_balance', True)), fields=('account', 'default_balance'), name='unique_default_balance'),
        ),
    ]
