# Generated by Django 4.2 on 2023-04-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_preferred_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pending_verification',
            field=models.BooleanField(default=True),
        ),
    ]
