# Generated by Django 4.2 on 2023-04-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_pending_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='use_2fa',
            field=models.BooleanField(default=False),
        ),
    ]
