name: Deploy to a VM at my house

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  release:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Create .env
        run: |
          touch .env
          echo DJANGO_SECRET_KEY=${{ secrets.SECRET_KEY }} >> .env
          echo DJANGO_TOTP_KEY=${{ secrets.TOTP_KEY }} >> .env
      - name: Build the Docker image
        run: docker compose build
      - name: Push to private registry
        run: docker compose push
  deploy-job:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Copy docker-compose.yml
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: docker-compose.yml
          target: /tmp
      - name: SSH to server and run docker compose
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd /tmp
            rm .env
            touch .env
            echo SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }} >> .env
            echo TOTP_KEY=${{ secrets.DJANGO_TOTP_KEY }} >> .env
            docker compose pull
            docker compose up -d --force-recreate
            docker ps