name: Develop branch integration

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  SECRET_KEY: 185c6bc55723fd8b1b005536c2a92fcf62e167e0a775015664
  TOTP_KEY: FX7ZQHIT7VWAM75MMDHD2S3WDQLXS

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests and Coverage report
        run: |
          coverage run manage.py test
          coverage report
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
